[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
anonymous_feedback ='0x0dc80a9f9c33215a41a19b15635659ea6380734df94b3ea5d6ecbe0910fc2cc8'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]